---
title: "Week 5"
description: "Data summarizing, reshaping, and wrangling with multiple tables"
date: "2/7/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Post-class updates 

Updates made on 2/9/24

* HW 5: see the updated HW 5 assignment on OneDrive called `hw_05_b526_v2.qmd`
* Midterm: due date extended to 2/25/24. 
    * See the updated midterm file on OneDrive with new yaml, due date, and links to previous midterm projects.
* Material covered in class on 2/7/24
    * Part 5 Sections 1-4.4
    * Solutions to Challenge 1 from section 4.3 of the Part 5 notes are in OneDrive (`Challenge_1_solutions_Part5.html`)

## Topics

-   **Practice** loading data and using `mutate()` and `separate()`
-   **Practice** using `here()` to load data in a subfolder of the project
-   **Learn** how to `summarize()` data with `group_by()` to summarize within categories
-   **Learn** and **apply** `bind_rows()` to combine rows from two or more datasets
-   **Learn** about the different kinds of joins and how they merge data
-   **Apply** `inner_join()` and `left_join()` to join tables on columns
-   **Utilize** `pivot_longer()` to make a *wide* dataset *long*



## Announcements

* Class materials for BSTA 526 will be provided in the shared OneDrive folder [BSTA_526_W24_class_materials_public](https://ohsuitg-my.sharepoint.com/:f:/g/personal/niederha_ohsu_edu/EvZ5qnesTopKqFWN2_hqEsYBLKZmJDjVxrPCbQOpvAIYSg?e=RDggRF). 
* For today's class, make sure to download to your computer the folder called `part_05`, and then open RStudio by double-clicking on the file called `part_05.Rproj`.


## Class materials

* [Readings](../readings/05-reading.qmd)
* One Drive [part_05 Project folder](https://ohsuitg-my.sharepoint.com/:f:/g/personal/niederha_ohsu_edu/EvZ5qnesTopKqFWN2_hqEsYBLKZmJDjVxrPCbQOpvAIYSg?e=RDggRF)

## Post-class survey

* Please fill out the [post-class survey](https://ohsu.ca1.qualtrics.com/jfe/form/SV_5urkrdktEwkQqEu) to provide feedback. Thank you!

## Homework

* See OneDrive folder for homework assignment.
* HW 5 due on 2/14. 
    * *See the updated HW 5 assignment on OneDrive called `hw_05_b526_v2.qmd`*

## Recording

* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-526-1-AX-W24/tool/a973f2a2-ea06-4734-aab7-a066c5573ca6/ShowPage?returnView=&studentItemId=0&backPath=&bltiAppStores=false&errorMessage=&clearAttr=&messageId=&source=&title=&newTopLevel=false&sendingPage=190949&postedComment=false&addBefore=&itemId=5172228&path=push&topicId=&addTool=-1&recheck=&id=&forumId=). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page. 


# Feedback from post-class surveys

* Week 5 feedback will be added during Week 6.
* See Week 4 page for [Week 4 feedback](week_04.qmd#muddiest-points-from-week-4).
